version: '3'
services:
  rakuten:
    build:
      context: .
    restart: always
    container_name: 'rakuten'
    working_dir: '/webapp'
    command: bash -C "pip install pipenv && pipenv lock -r > requirements.txt && pip install -r requirements.txt $$ pip install mysqlclient"
    tty: true
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_HOST}
    volumes:
      - .:/webapp

  mysql:
    image: mysql:5.7
    hostname: rakuten_db_mysql
    restart: 'always'
    env_file:
      - .env
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      # 初期データを投入するSQLが格納されているdir
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_HOST}
      TZ: "Asia/Tokyo"
      BIND-ADDRESS: 0.0.0.0
    expose:
      - '3306'
    ports:
      - "3306:3306"
    tty: true
